"""add pro subscription fields

Revision ID: 0ab8ec596729
Revises: 456369faa9f4
Create Date: 2026-08-10 18:38:58.420058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab8ec596729'
down_revision: Union[str, None] = '456369faa9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('pro_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expires_at')
    op.drop_column('users', 'is_pro')
    # ### end Alembic commands ###
