"""add pro_coins to users

Revision ID: 1976f3a47d31
Revises: a063b6f03f67
Create Date: 2026-08-04 15:50:14.468888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1976f3a47d31'
down_revision: Union[str, None] = 'a063b6f03f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_coins', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_coins')
    # ### end Alembic commands ###
