"""add gamification and perimetria fields

Revision ID: a063b6f03f67
Revises: ab3be94ca329
Create Date: 2026-08-04 14:13:41.201012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a063b6f03f67'
down_revision: Union[str, None] = 'ab3be94ca329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_measurements', sa.Column('body_fat_percent', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('coins', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coins')
    op.drop_column('body_measurements', 'body_fat_percent')
    # ### end Alembic commands ###
