"""add is_epic to goals

Revision ID: bc998a2200b3
Revises: 52d67f2e800c
Create Date: 2026-08-06 16:40:53.372513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc998a2200b3'
down_revision: Union[str, None] = '52d67f2e800c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('is_epic', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'is_epic')
    # ### end Alembic commands ###
