"""add_is_rest_day_to_workout_sessions

Revision ID: c65f4cd3d575
Revises: bc998a2200b3
Create Date: 2026-08-07 13:34:31.564827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65f4cd3d575'
down_revision: Union[str, None] = 'bc998a2200b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('is_rest_day', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('workout_sessions', 'workout_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'workout_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('workout_sessions', 'is_rest_day')
    # ### end Alembic commands ###
